### ISSUE TITLE
API Error with fox/foxes

### ISSUE THREAD

**Issue by fangykai** [skeith/MayuYukirin#20]
Using the API for fox `http://wohlsoft.ru/images/foxybot/randomfox.php` seems to be throwing an error. Website doesn't respond on my end or is very slow. Would it be possible to change it to `https://randomfox.ca/floof/` ?

**Comment by skeith** [comment]
I just checked the API and it is working properly. Care to try again?

**Comment by fangykai** [comment]
Hey there, works now! Sorry for creating this!
